const BOARD_MIN_WIDTH = 300;
const BOARD_MAX_WIDTH = 1000;
const BOARD_MIN_HEIGHT = 300;
const BOARD_MAX_HEIGHT = 1000;
const BOARD_MIN_ROWS = 1;
const BOARD_MAX_ROWS = 10;
const BOARD_MIN_COLS = 1;
const BOARD_MAX_COLS = 10;
const BOARD_DEFAULT_PARAMS = {
  width: 500,
  height: 500,
  columns: 5,
  rows: 5
};

export {
  BOARD_MIN_WIDTH,
  BOARD_MAX_WIDTH,
  BOARD_MIN_HEIGHT,
  BOARD_MAX_HEIGHT,
  BOARD_MIN_ROWS,
  BOARD_MAX_ROWS,
  BOARD_MIN_COLS,
  BOARD_MAX_COLS,
  BOARD_DEFAULT_PARAMS
};
