const TABLE_MIN_WIDTH = 300;
const TABLE_MAX_WIDTH = 1000;
const TABLE_MIN_HEIGHT = 300;
const TABLE_MAX_HEIGHT = 1000;
const TABLE_MIN_ROWS = 1;
const TABLE_MAX_ROWS = 10;
const TABLE_MIN_COLS = 1;
const TABLE_MAX_COLS = 10;
const TABLE_DEFAULT_PARAMS = {
  width: 400,
  height: 400,
  columns: 5,
  rows: 5
};

export {
  TABLE_MIN_WIDTH,
  TABLE_MAX_WIDTH,
  TABLE_MIN_HEIGHT,
  TABLE_MAX_HEIGHT,
  TABLE_MIN_ROWS,
  TABLE_MAX_ROWS,
  TABLE_MIN_COLS,
  TABLE_MAX_COLS,
  TABLE_DEFAULT_PARAMS
};
